add icon url
HackRegina/hackathon-starter-kit pull request #1
Opened 2018-11-26 18:24 UTC by trollmad3

this is one of my favorite icon url

2018-12-02 05:22 UTC, lucastetreault requested changes

2018-12-02 05:22 UTC, lucastetreault commented on README.md
> +Cool small icons that are easy to recognize.
Looks like you put your changes between the font awesome link and its description by accident. Please follow the same format as has been established - the link on one line, followed by the description. Thanks.

2018-12-02 15:53 UTC, trollmad3 commented on README.md
> +Cool small icons that are easy to recognize.
Did the new commit fix it?

2021-02-03 19:03 UTC, DJCrossman approved these changes

2021-02-03 19:03 UTC, merged

2021-02-04 04:24 UTC, Aholicknight commented
yay it was finally merged